# fly.toml app configuration file generated for kalenteri-bot on 2024-01-15T00:44:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kalenteri-bot"
primary_region = "arn"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
